### PR TITLE
add analyticaljacvec operator

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Fixes https://github.com/JuliaDiffEq/DiffEqOperators.jl/issues/176 @rveltz try it out?

### CODE REVIEW

**Comment by rveltz** [comment]
Hi,

It works but I had to correct a few typos. Should I paste the corrected code `jacvec_operators.jl` in here?

Thank you a lot for your work to making this happens.

> I want to use stiff solvers on GPU, I still have to implement a linear solver in your interface

**Comment by ChrisRackauckas** [comment]
>I want to use stiff solvers on GPU, I still have to implement a linear solver in your interface

The default linear solver should use a QR that works?

**Comment by rveltz** [comment]
I have to write a wrap to `KrylovKit` as you did for `LinearSolver`. What about my question about `jacvec_operators.jl`?

**Comment by ChrisRackauckas** [comment]
Yes, please PR to this PR if you have the stuff to finish it!

>I have to write a wrap to KrylovKit as you did for LinearSolver.

`LinSolveGMRES` doesn't work with GPUs? If not, I think it would be good to add the KrylovKit stuff to DiffEqBase with an `@requires` and get it documented.

**Comment by rveltz** [comment]
`LinSolveGMRES doesn't work with GPUs?` I think so. It is just that I use `KrylovKit` in my work for several reasons as I exposed on discourse.

As for the PR, I will try my best. A PR to a PR for my very first PR seems engaging :D

**Comment by ChrisRackauckas** [comment]
>LinSolveGMRES doesn't work with GPUs? I think so. It is just that I use KrylovKit in my work for several reasons as I exposed on discourse.

Interesting, can you link to it? I haven't found benchmarks between the two. It would likely be very beneficial to add this `ComposePreconditioner` by default to KrylovKit as well:

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/linear_nonlinear.jl#L146-L221

**Comment by rveltz** [comment]
OK...I messed up :( I think you can see my PR [here](https://github.com/rveltz/DiffEqOperators.jl/pull/1)

The discourse post is [here](https://discourse.julialang.org/t/nonlinear-equations-on-abstract-vectors/28692/5)

I think `IterativeSolvers` is a bit faster than `KrylovKit`. We should probably add `struct LinKrylovKit` first.

**Comment by ChrisRackauckas** [comment]
>We should probably add struct LinKrylovKit first.

Yes, let's continue this.

**Comment by rveltz** [comment]
> Yes, let's continue this.

I messed up again but [see](https://github.com/rveltz/DiffEqBase.jl/pull/1)

**Pull request merged**
