### PR TITLE
Matrix-free operator

### PR DESCRIPTION
**Pull request by YingboMa**
A matrix-free operator was brought up in https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/162.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Yeah I don't see an issue with this approach.

**Comment by chiyahn** [comment]
Seems like defining an `ODEProblem` using the matrix-free operator returns an error:
```julia
import DiffEqOperators, OrdinaryDiffEq
f = cumsum!
args = nothing
A = MatrixFreeOperator(f,args)
b = rand(5)

# definte the corresponding ODEProblem
ODEProblem(A,b,(0.0,1.0)) # returns an error
```
Running the code above returns the following error in my computer (Win10, Julia 1.0):
```julia
ArgumentError: reducing over an empty collection is not allowed

Stacktrace:
 [1] _empty_reduce_error() at .\reduce.jl:214
 [2] reduce_empty(::Function, ::Type) at .\reduce.jl:224
 [3] mapreduce_empty(::typeof(identity), ::Function, ::Type) at .\reduce.jl:249
 [4] _mapreduce(::typeof(identity), ::typeof(max), ::IndexLinear, ::Array{Any,1}) at .\reduce.jl:303
 [5] _mapreduce_dim at .\reducedim.jl:305 [inlined]
 [6] #mapreduce#538 at .\reducedim.jl:301 [inlined]
 [7] mapreduce at .\reducedim.jl:301 [inlined]
 [8] _maximum at .\reducedim.jl:650 [inlined]
 [9] _maximum at .\reducedim.jl:649 [inlined]
 [10] #maximum#544 at .\reducedim.jl:645 [inlined]
 [11] maximum(::Array{Any,1}) at .\reducedim.jl:645
 [12] numargs(::MatrixFreeOperator{typeof(cumsum!),Nothing}) at C:\Users\Chiyoung Ahn\.julia\packages\DiffEqBase\WzpM7\src\utils.jl:13
 [13] isinplace(::MatrixFreeOperator{typeof(cumsum!),Nothing}, ::Int64) at C:\Users\Chiyoung Ahn\.julia\packages\DiffEqBase\WzpM7\src\utils.jl:26
 [14] #ODEFunction#111(::Base.Iterators.Pairs{Symbol,Nothing,NTuple{7,Symbol},NamedTuple{(:analytic, :tgrad, :jac, :invW, :invW_t, :paramjac, :syms),NTuple{7,Nothing}}}, ::Type, ::MatrixFreeOperator{typeof(cumsum!),Nothing}) at C:\Users\Chiyoung Ahn\.julia\packages\DiffEqBase\WzpM7\src\diffeqfunction.jl:213
 [15] (::getfield(Core, Symbol("#kw#Type")))(::NamedTuple{(:analytic, :tgrad, :jac, :invW, :invW_t, :paramjac, :syms),NTuple{7,Nothing}}, ::Type{ODEFunction}, ::MatrixFreeOperator{typeof(cumsum!),Nothing}) at .\none:0
 [16] convert(::Type{ODEFunction}, ::MatrixFreeOperator{typeof(cumsum!),Nothing}) at C:\Users\Chiyoung Ahn\.julia\packages\DiffEqBase\WzpM7\src\diffeqfunction.jl:505
 [17] #ODEProblem#300(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Type, ::MatrixFreeOperator{typeof(cumsum!),Nothing}, ::Array{Float64,1}, ::Tuple{Float64,Float64}, ::Nothing) at C:\Users\Chiyoung Ahn\.julia\packages\DiffEqBase\WzpM7\src\problems\ode_problems.jl:34
 [18] Type at C:\Users\Chiyoung Ahn\.julia\packages\DiffEqBase\WzpM7\src\problems\ode_problems.jl:34 [inlined] (repeats 2 times)
 [19] top-level scope at In[10]:6
```

**Comment by chiyahn** [comment]
Update: I can confirm that the recent commit https://github.com/JuliaDiffEq/DiffEqOperators.jl/pull/81/commits/7a4b28d1a794940f4bae85d099995ac4e8a4538e resolved the issue I had at https://github.com/JuliaDiffEq/DiffEqOperators.jl/pull/81#issuecomment-431474417.

**Comment by ChrisRackauckas** [comment]
We'll probably want `update_coefficients!` and all of that soon, but for now this seems functional enough.

**Pull request merged**
