### PR TITLE
[WIP] GhostDerivativeOperator and Compositions

### PR DESCRIPTION
**Pull request by ajozefiak**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Looking great. Let's merge and handle the test failure by fixing those convolution dispatching in a follow up PR.

**Comment by ajozefiak** [comment]
I think that test was working actually, my comment should have read that the "third" test is failing.

**Comment by ChrisRackauckas** [comment]
oh which test is failing?

**Comment by ajozefiak** [comment]
Expression: A * u ≈ L * (Q * u)
BoundsError: attempt to access 20-element Array{Float64,1} at index [21]

**Comment by ajozefiak** [comment]
I think Shivin's index fix broke something. I was passing all tests locally (except the one I left as broken) before pushing the branch.

**Comment by ChrisRackauckas** [comment]
It was failing before that was merged. See your first commit failed. Shivin's was passing tests.

**Pull request merged**
